language: python
python:
  - 2.6
  - 2.7
install:
  - python build.py dev
script: python build.py analyse
notifications:
  email: false
  irc: 
    channels:
      - "irc.freenode.org#aspen"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
